const { supabaseAdmin } = require('../config/supabase');
const logger = require('../utils/logger');

/**
 * AI Service – mock implementations for MVP.
 * Each method is structured so a real AI provider can replace the mock
 * logic without changing the controller or route layer.
 *
 * All AI generation results are stored in the ai_generations table for audit.
 */
const aiService = {
  /**
   * Enhance a product image (mock).
   */
  async enhanceImage(imageUrl, userId, productId = null) {
    // Mock response — replace with real AI call later
    const result = {
      enhancedImageUrl: imageUrl, // Return the same URL as mock
      status: 'mock',
    };

    await this._saveGeneration(userId, productId, 'image_enhancement', result);
    return result;
  },

  /**
   * Convert speech to text (mock).
   */
  async speechToText(audioData, userId, productId = null) {
    const result = {
      transcript: 'This is a sample transcript generated by the mock AI service. Replace with real speech-to-text integration.',
      language: 'en',
      confidence: 0.95,
      status: 'mock',
    };

    await this._saveGeneration(userId, productId, 'speech_to_text', result);
    return result;
  },

  /**
   * Generate a product description from keywords (mock).
   */
  async generateDescription({ language, category, keywords }, userId, productId = null) {
    const keywordStr = keywords.join(', ');
    const result = {
      title: `Traditional ${category} - ${keywords[0] || 'Handcrafted'} Art`,
      description: `A beautiful ${category.toLowerCase()} piece featuring ${keywordStr}. Handcrafted using traditional techniques passed down through generations. Each piece is unique and showcases the exceptional skill of Indian artisans.`,
      language,
      status: 'mock',
    };

    await this._saveGeneration(userId, productId, 'description_generation', result);
    return result;
  },

  /**
   * Suggest a price for a product (mock).
   */
  async suggestPrice({ category, description, materials }, userId, productId = null) {
    // Simple mock pricing based on category
    const basePrices = {
      Textiles: 2500,
      Handicrafts: 1500,
      Pottery: 800,
      Jewelry: 3500,
      Woodwork: 2000,
      Painting: 5000,
      'Home Decor': 1200,
    };

    const basePrice = basePrices[category] || 1000;
    const result = {
      suggestedPrice: basePrice,
      minPrice: Math.round(basePrice * 0.7),
      maxPrice: Math.round(basePrice * 1.5),
      currency: 'INR',
      status: 'mock',
    };

    await this._saveGeneration(userId, productId, 'price_suggestion', result);
    return result;
  },

  /**
   * Save an AI generation record for audit / analytics.
   * @private
   */
  async _saveGeneration(userId, productId, type, response) {
    try {
      await supabaseAdmin
        .from('ai_generations')
        .insert({
          user_id: userId,
          product_id: productId,
          type,
          response,
        });
    } catch (err) {
      // Non-critical — log but don't fail the main operation
      logger.warn(`Failed to save AI generation record: ${err.message}`);
    }
  },
};

module.exports = aiService;
